networks:
  optimism:
    name: optimism

volumes:
  config:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_config
  scripts:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_scripts
  shared:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_shared
  downloads:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_downloads
  influxdb:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_influxdb
  l2geth:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_l2geth
  op-geth:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_op-geth

services:
  l2geth:
    image: ethereumoptimism/l2geth:${L2GETH_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-l2geth
    restart: on-failure
    stop_grace_period: 5m
    entrypoint: 
      - /bin/sh
      - -c
      - "/scripts/init-l2geth.sh && /scripts/start-l2geth.sh"
    env_file:
      - optimism.env
      - ./envs/l2geth.env
    volumes:
      - ${L2GETH_DATABASE_PATH:-l2geth}:/geth
      - ${SCRIPTS_PATH:-scripts}:/scripts/
    expose:
      - 8545 # http
      - 8546 # ws
    networks:
      - optimism

  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:${OP_GETH_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-op-geth
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-geth.sh
    env_file:
      - optimism.env
      - ./envs/op-geth.env
    volumes:
      - ${CONFIG_PATH:-config}:/chainconfig
      - ${SCRIPTS_PATH:-scripts}:/scripts
      - ${SHARED_PATH:-shared}:/shared
      - ${OPGETH_DATABASE_PATH:-op-geth}:/geth
    ports:
      - 39393:39393/udp # p2p
      - 39393:39393/tcp # p2p
      - 127.0.0.1:9993:8545 # http
      # - 127.0.0.1:9994:8546 # ws
    expose:
      # - 8545
      - 8546
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - optimism
    environment:
      LETSENCRYPT_HOST: ${SUBDOMAIN:-optimism}.${HOST}
      VIRTUAL_HOST_MULTIPORTS: |-
        ${SUBDOMAIN:-optimism}.${HOST}:
          "/":
            port: 8545
            dest: "/"
          "/ws":
            port: 8546
            dest: "/"

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:${OP_NODE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-op-node
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-node.sh
    env_file:
      - optimism.env
      - ./envs/op-node.env
    volumes:
      - ${CONFIG_PATH:-config}:/chainconfig
      - ${SCRIPTS_PATH:-scripts}:/scripts
      - ${SHARED_PATH:-shared}:/shared
    ports:
      - 9003:9003/udp # p2p
      - 9003:9003/tcp # p2p
      # - 127.0.0.1:9545:9545 # http
    expose:
      - 9545 # http
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - optimism

  bedrock-init:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.bedrock-init
    container_name: ${COMPOSE_PROJECT_NAME}-bedrock-init
    entrypoint: /scripts/init-bedrock.sh
    env_file:
      - optimism.env
      - ./envs/op-geth.env
    volumes:
      - ${SCRIPTS_PATH:-scripts}:/scripts
      - ${SHARED_PATH:-shared}:/shared
      - ${OPGETH_DATABASE_PATH:-op-geth}:/geth
      - ${L2GETH_DATABASE_PATH:-l2geth}:/legacy-geth
      - ${DOWNLOADS_PATH:-downloads}:/downloads
    networks:
      - optimism

  influxdb:
    image: influxdb:${INFLUXDB_TAG:-1.8}
    container_name: ${COMPOSE_PROJECT_NAME}-influxdb
    restart: unless-stopped
    env_file:
      - optimism.env
      - ./envs/influxdb.env
    volumes:
      - ${SCRIPTS_PATH:-scripts}/influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql
      - ${INFLUXDB_PATH:-influxdb}:/var/lib/influxdb
    # ports:
    #   - 8086:8086
    expose:
      - 8086
    networks:
      - optimism
