version: '3.9'

volumes:
  dtl:
  geth:

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  dtl:
    image: ethereumoptimism/data-transport-layer:${IMAGE_TAG__DTL:-latest}
    restart: unless-stopped
    entrypoint: /scripts/dtl-start.sh
    environment:
      SYNC_SOURCE: l1
      DATA_TRANSPORT_LAYER__RPC_ENDPOINT: ${ETHEREUM_RPC}
    env_file:
      - ./envs/dtl.env
    volumes:
      - dtl:/db
      - ./scripts/:/scripts/
    ports:
      - ${PORT__DTL:-7878}:7878
    <<: *logging

  l2geth:
    image: ethereumoptimism/l2geth:${IMAGE_TAG__L2GETH:-latest}
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: 
      - /bin/sh
      - -c
      - "/scripts/l2geth-init.sh && /scripts/l2geth-start.sh"
    environment:
      SYNC_SOURCE: l1
      NODE_TYPE: archive
    env_file:
      - ./envs/l2geth.env
    ports:
      - ${PORT__L2GETH_HTTP:-9991}:9991 # 8545
      - ${PORT__L2GETH_WS:-9992}:9992 #8546
    volumes:
      # - geth:/geth
      - /home/optimism-data:/geth
      - ./scripts/:/scripts/
    <<: *logging