volumes:
  config:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_config

profiles:
  create-volume:
    volumes:
      data:
        name: ${COMPOSE_PROJECT_NAME}_data

networks:
  mainnet:
    name: mainnet

services:
  mainnet:
    image: thorax/erigon:${MAINNET_ERIGON_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - mainnet
    volumes:
      - config:/home/erigon/.config
      - ${DATABASE_PATH:-data}:/home/erigon/.local/share/erigon
    ports:
      - 30303:30303/tcp # eth/66 peering
      - 30303:30303/udp # eth/66 peering
      - 30304:30304/tcp # eth/67 peering
      - 30304:30304/udp # eth/67 peering
      - 42069:42069/tcp # snap sync
      - 42069:42069/udp # snap sync
      - 4000:4000/udp # sentinel peering (caplin)
      - 4001:4001/tcp # sentinel peering (caplin)
      - 127.0.0.1:8545:8545/tcp # HTTP & WebSockets & GraphQL
    expose:
      - 9090/tcp # gRPC Server
      - 8551/tcp # Engine API (JWT auth)
      - 9091/tcp # incoming gRPC Connections
      - 6060/tcp # metric
      - 6061/tcp # pprof
      - 5555/tcp # beaconAPI
      # - 8545/tcp # HTTP & WebSockets & GraphQL
    command: >
      --config /home/erigon/.config/config.yaml
    mem_swappiness: 0
    user: ${ERIGON_UID:-1000}:${ERIGON_GID:-1000}
    environment:
      VIRTUAL_HOST: ${SUBDOMAIN:-mainnet}.${HOST}
      VIRTUAL_PORT: 8545
      LETSENCRYPT_HOST: ${SUBDOMAIN:-mainnet}.${HOST}
