volumes:
  config:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_config
  data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_data

networks:
  mainnet:
    name: ${COMPOSE_PROJECT_NAME}

services:
  mainnet:
    image: erigontech/erigon:${ERIGON_TAG:-v3.0.1}
    container_name: ${COMPOSE_PROJECT_NAME}
    sysctls:
      net.ipv4.tcp_slow_start_after_idle: 0
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_rmem: 4096 87380 16777216
      net.ipv4.tcp_wmem: 4096 87380 16777216
      net.core.somaxconn: 32768
      # net.core.netdev_max_backlog: 50000
      net.ipv4.tcp_max_syn_backlog: 30000
      net.ipv4.tcp_max_tw_buckets: 2000000
    ulimits:
      nofile: 1048576
      memlock: -1
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - mainnet
    volumes:
      - ${CONFIG_PATH:-config}:/home/erigon/.config
      - ${DATABASE_PATH:-data}:/home/erigon/.local/share/erigon
    ports:
      - ${PORT_PEERING_66:-30303}:30303/tcp # eth/66 peering
      - ${PORT_PEERING_66:-30303}:30303/udp # eth/66 peering
      - ${PORT_PEERING_67:-30304}:30304/tcp # eth/67 peering
      - ${PORT_PEERING_67:-30304}:30304/udp # eth/67 peering
      - ${PORT_SNAP:-42069}:42069/tcp # snap sync
      - ${PORT_SNAP:-42069}:42069/udp # snap sync
      - ${PORT_SENTINEL_UDP:-4000}:4000/udp # sentinel peering (caplin)
      - ${PORT_SENTINEL_TCP:-4001}:4001/tcp # sentinel peering (caplin)
      # - 127.0.0.1:8545:8545/tcp # HTTP & WebSockets & GraphQL
      # - 5555:5555/tcp # beaconAPI
    expose:
      - 9090/tcp # gRPC Server
      - 8551/tcp # Engine API (JWT auth)
      - 9091/tcp # incoming gRPC Connections
      - 6060/tcp # metric
      - 6061/tcp # pprof
      - 5555/tcp # beaconAPI
      - 8545/tcp # HTTP & WebSockets & GraphQL
    command: >
      --config /home/erigon/.config/config.yaml
    mem_swappiness: 0
    user: ${ERIGON_UID:-1000}:${ERIGON_GID:-1000}
    environment:
      LETSENCRYPT_HOST: ${SUBDOMAIN:-mainnet}.${HOST}
      VIRTUAL_HOST_MULTIPORTS: |-
        ${SUBDOMAIN:-mainnet}.${HOST}:
          "/":
            port: 8545
            dest: "/"
          "/eth/v1":
            port: 5555
            dest: "/eth/v1"
