networks:
  arbitrum-one:
    name: ${COMPOSE_PROJECT_NAME}
  nitro-data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_nitro-data
  classic-data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_classic-data

services:
  arbitrum-one-nitro:
    image: offchainlabs/nitro-node:${ARBITRUM_NITRO_TAG:-v3.6.8-d6c96a5}
    container_name: ${COMPOSE_PROJECT_NAME}-nitro
    sysctls:
      net.ipv4.tcp_slow_start_after_idle: 0       # Disable slow start after idle
      net.ipv4.tcp_no_metrics_save: 1             # Disable metrics cache
      net.ipv4.tcp_rmem: 4096 87380 16777216      # Increase TCP read buffers
      net.ipv4.tcp_wmem: 4096 87380 16777216      # Increase TCP write buffers
      net.core.somaxconn: 32768                   # Higher connection queue
      # net.core.netdev_max_backlog: 50000          # Increase network buffer
      net.ipv4.tcp_max_syn_backlog: 30000         # More SYN requests
      net.ipv4.tcp_max_tw_buckets: 2000000        # Allow more TIME_WAIT sockets
    ulimits:
      nofile: 1048576
    restart: unless-stopped
    stop_grace_period: 30s
    user: root
    networks:
      - arbitrum-one
    volumes:
      - ${NITRO_DATABASE_PATH:-nitro-data}:/home/user/.arbitrum
    # ports:
    #   - 127.0.0.1:8547:8547/tcp # http
    expose:
      - 8547 # http
      - 8548 # ws
    command:
      - --init.url=https://snapshot.arbitrum.foundation/arb1/nitro-archive.tar
      - --execution.caching.archive=true
      - --execution.caching.database-cache=2048
      - --execution.caching.snapshot-cache=400
      - --execution.caching.trie-clean-cache=600
      - --execution.caching.trie-dirty-cache=1024
      - --execution.rpc.classic-redirect=http://${COMPOSE_PROJECT_NAME}-classic:8547
      - --execution.rpc.gas-cap=5500000000
      - --execution.rpc.log-history=0
      #- --execution.rpc.tx-fee-cap=0
      - --execution.sequencer.enable=false
      - --persistent.chain=/home/user/.arbitrum/data
      - --persistent.global-config=/home/user/.arbitrum
      - --parent-chain.connection.url=${MAINNET_RPC_EXECUTION}
      - --parent-chain.blob-client.beacon-url=${MAINNET_RPC_CONSENSUS}
      - --chain.id=42161
      - --http.api=eth,net,web3,arb,txpool,debug
      - --http.corsdomain=*
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      # - --ws.port=8547
      - --node.batch-poster.enable=false
      - --node.sequencer=false
      - --node.staker.enable=false
    environment:
      LETSENCRYPT_HOST: ${SUBDOMAIN:-arbitrum-one}.${HOST}
      VIRTUAL_HOST_MULTIPORTS: |-
        ${SUBDOMAIN:-arbitrum-one}.${HOST}:
          "/":
            port: 8547
            dest: "/"
          "/ws":
            port: 8548
            dest: "/"

  arbitrum-one-classic:
    image: offchainlabs/arb-node:${ARBITRUM_CLASSIC_TAG:-v1.4.5-e97c1a4}
    container_name: ${COMPOSE_PROJECT_NAME}-classic
    sysctls:
      net.ipv4.tcp_slow_start_after_idle: 0       # Disable slow start after idle
      net.ipv4.tcp_no_metrics_save: 1             # Disable metrics cache
      net.ipv4.tcp_rmem: 4096 87380 16777216      # Increase TCP read buffers
      net.ipv4.tcp_wmem: 4096 87380 16777216      # Increase TCP write buffers
      net.core.somaxconn: 32768                   # Higher connection queue
      # net.core.netdev_max_backlog: 50000          # Increase network buffer
      net.ipv4.tcp_max_syn_backlog: 30000         # More SYN requests
      net.ipv4.tcp_max_tw_buckets: 2000000        # Allow more TIME_WAIT sockets
    ulimits:
      nofile: 1048576    # Max open files (for RPC/WS connections)
    restart: unless-stopped
    stop_grace_period: 30s
    user: root
    networks:
      - arbitrum-one
    volumes:
      - ${CLASSIC_DATABASE_PATH:-classic-data}:/home/user/.arbitrum/mainnet
    expose:
      - 8547 # http
      - 8548 # ws
    command:
      - --l1.url=${MAINNET_RPC_EXECUTION}
      - --l2.disable-upstream
      - --node.chain-id=42161
      - --node.cache.allow-slow-lookup
      - --node.rpc.addr=0.0.0.0
      - --node.rpc.enable-l1-calls
      - --node.rpc.tracing.enable
      - --node.rpc.tracing.namespace=trace
      - --core.checkpoint-pruning-mode=off
      - --core.checkpoint-gas-frequency=156250000
      # - --core.lazy-load-core-machine
