networks:
  arbitrum-one:
    name: arbitrum-one
  mainnet:
    external: true
    name: mainnet

services:
  arbitrum-one-nitro:
    image: offchainlabs/nitro-node:${ARBITRUM_NITRO_TAG:-v2.3.4-b4cc111}
    container_name: ${COMPOSE_PROJECT_NAME}-nitro
    restart: unless-stopped
    stop_grace_period: 30s
    user: root
    networks:
      - arbitrum-one
      - mainnet
    volumes:
      - /data/arbitrum-one/nitro:/home/user/.arbitrum
    # ports:
      # - 127.0.0.1:8547:8547/tcp # http
      # - 8547:8547/tcp # http
    expose:
      - 8547 # http
      - 8548 # ws
    command:
      - --init.url=https://snapshot.arbitrum.foundation/arb1/nitro-archive.tar
      - --execution.caching.archive
      - --persistent.chain=/home/user/.arbitrum/data
      - --persistent.global-config=/home/user/.arbitrum
      - --execution.rpc.classic-redirect=http://${COMPOSE_PROJECT_NAME}-classic:8547
      - --parent-chain.connection.url=${MAINNET_RPC_EXECUTION}
      - --parent-chain.blob-client.beacon-url=${MAINNET_RPC_CONSENSUS}
      - --chain.id=42161
      - --http.api=net,web3,eth,debug 
      - --http.corsdomain=* 
      - --http.addr=0.0.0.0 
      - --http.vhosts=*   
      # - --ws.port=8547
      # - --ws.addr=0.0.0.0
      # - --ws.origins=*
    environment:
      VIRTUAL_HOST: arbitrum-one.${HOST}
      VIRTUAL_PORT: 8547
      LETSENCRYPT_HOST: arbitrum-one.${HOST}

  arbitrum-one-classic:
    image: offchainlabs/arb-node:${ARBITRUM_CLASSIC_TAG:-v1.4.5-e97c1a4}
    container_name: ${COMPOSE_PROJECT_NAME}-classic
    restart: unless-stopped
    stop_grace_period: 30s
    user: root
    networks:
      - arbitrum-one
      - mainnet
    volumes:
      - /data/arbitrum-one/classic:/home/user/.arbitrum/mainnet
    expose:
      - 8547 # http
      - 8548 # ws
    command:
      - --l1.url=${MAINNET_RPC_EXECUTION}
      - --l2.disable-upstream
      - --node.chain-id=42161
      - --node.rpc.tracing.enable
      - --node.rpc.tracing.namespace=trace
      - --core.checkpoint-pruning-mode=off
      - --node.cache.allow-slow-lookup
      - --core.checkpoint-gas-frequency=156250000
      - --node.rpc.addr=0.0.0.0
      # - --core.lazy-load-core-machine