chain : mainnet
datadir : /home/erigon/.local/share/erigon
externalcl: true
port : 30303
private.api.addr : localhost:9090
rpc.returndata.limit: 1000000
# rpc.accessList : rules.json

http : true
# http.compression : true 
http.port : 8545
http.addr : 0.0.0.0
http.vhosts : "*"
http.corsdomain : "*"
http.api : [eth, erigon, web3, debug, net, trace, txpool]

ws : true
# ws.compression : true

authrpc.port : 8551
authrpc.addr : 0.0.0.0
authrpc.vhosts : "*"
authrpc.jwtsecret : /home/erigon/.local/share/erigon/jwt.hex

torrent.port : 42069
torrent.download.rate : 20mb
torrent.upload.rate : 20mb

metrics : true
metrics.addr : 0.0.0.0 
metrics.port : 6060

pprof : true
pprof.addr : 0.0.0.0
pprof.port : 6061