volumes:
  data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_data
  scripts:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_scripts
  shared:

networks:
  opstack:
    name: ${COMPOSE_PROJECT_NAME}

services:
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:${OPNODE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-op-node
    ports:
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
    expose:
      - 8545     # RPC
      - 7300     # metrics
      - 6060     # pprof
    environment:
      - OPSTACK_CHAIN=${CHAIN}
      - OP_NODE_SYNCMODE=execution-layer
      - OP_NODE_VERIFIER_L1_CONFS=4
      - OP_NODE_ROLLUP_LOAD_PROTOCOL_VERSIONS=true
      - OP_NODE_L1_ETH_RPC=${L1_RPC_EXECUTION}
      - OP_NODE_L1_BEACON=${L1_RPC_CONSENSUS}
      - OP_NODE_L1_BEACON_ARCHIVER=${L1_RPC_CONSENSUS}
      # - OP_NODE_L1_BEACON_FETCH_ALL_SIDECARS="true"
      - OP_NODE_L1_RPC_KIND=${L1_RPC_KIND:-debug_geth}
      - OP_NODE_L1_TRUST_RPC=${L1_RPC_TRUST:-false}
      - OP_NODE_L2_ENGINE_KIND=${CLIENT}
      - OP_NODE_L2_ENGINE_RPC=http://${COMPOSE_PROJECT_NAME}-op-exec:8551 # ws://${COMPOSE_PROJECT_NAME}-op-${CLIENT}:8551
      - OP_NODE_L2_ENGINE_AUTH=/tmp/engine-auth-jwt
      # - OP_NODE_L2_SKIP_SYNC_START_CHECK=true
      - OP_NODE_LOG_LEVEL=info
      - OP_NODE_LOG_FORMAT=json
      - OP_NODE_SNAPSHOT_LOG=/tmp/op-node-snapshot-log
      - OP_NODE_METRIC_ENABLED=true
      - OP_NODE_METRICS_ADDR=0.0.0.0
      - OP_NODE_METRICS_PORT=7300
      - OP_NODE_RPC_ADDR=0.0.0.0
      - OP_NODE_RPC_PORT=8545
      - OP_NODE_P2P_AGENT=${CHAIN}
      - OP_NODE_P2P_LISTEN_IP=0.0.0.0
      - OP_NODE_P2P_LISTEN_TCP_PORT=9222
      - OP_NODE_P2P_LISTEN_UDP_PORT=9222
      - OP_NODE_INTERNAL_IP="true"
      # - OP_NODE_P2P_BOOTNODES=enr:-J24QNz9lbrKbN4iSmmjtnr7SjUMk4zB7f1krHZcTZx-JRKZd0kA2gjufUROD6T3sOWDVDnFJRvqBBo62zuF-hYCohOGAYiOoEyEgmlkgnY0gmlwhAPniryHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQKNVFlCxh_B-716tTs-h1vMzZkSs1FTu_OYTNjgufplG4N0Y3CCJAaDdWRwgiQG,enr:-J24QH-f1wt99sfpHy4c0QJM-NfmsIfmlLAMMcgZCUEgKG_BBYFc6FwYgaMJMQN5dsRBJApIok0jFn-9CS842lGpLmqGAYiOoDRAgmlkgnY0gmlwhLhIgb2Hb3BzdGFja4OFQgCJc2VjcDI1NmsxoQJ9FTIv8B9myn1MWaC_2lJ-sMoeCDkusCsk4BYHjjCq04N0Y3CCJAaDdWRwgiQG,enr:-J24QDXyyxvQYsd0yfsN0cRr1lZ1N11zGTplMNlW4xNEc7LkPXh0NAJ9iSOVdRO95GPYAIc6xmyoCCG6_0JxdL3a0zaGAYiOoAjFgmlkgnY0gmlwhAPckbGHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQJwoS7tzwxqXSyFL7g0JM-KWVbgvjfB8JA__T7yY_cYboN0Y3CCJAaDdWRwgiQG,enr:-J24QHmGyBwUZXIcsGYMaUqGGSl4CFdx9Tozu-vQCn5bHIQbR7On7dZbU61vYvfrJr30t0iahSqhc64J46MnUO2JvQaGAYiOoCKKgmlkgnY0gmlwhAPnCzSHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQINc4fSijfbNIiGhcgvwjsjxVFJHUstK9L1T8OTKUjgloN0Y3CCJAaDdWRwgiQG,enr:-J24QG3ypT4xSu0gjb5PABCmVxZqBjVw9ca7pvsI8jl4KATYAnxBmfkaIuEqy9sKvDHKuNCsy57WwK9wTt2aQgcaDDyGAYiOoGAXgmlkgnY0gmlwhDbGmZaHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQIeAK_--tcLEiu7HvoUlbV52MspE0uCocsx1f_rYvRenIN0Y3CCJAaDdWRwgiQG
    entrypoint: /scripts/op-node.sh
    restart: unless-stopped
    networks:
      - opstack
    volumes:
      - ${DATABASE_PATH:-data}:/data
      - ${SCRIPTS_PATH:-scripts}:/scripts
      - shared:/shared

  op-reth:
    profiles: ["reth"]
    image: ghcr.io/paradigmxyz/op-reth:${RETH_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-op-exec
    sysctls:
      net.ipv4.tcp_slow_start_after_idle: 0       # Disable slow start after idle
      net.ipv4.tcp_no_metrics_save: 1             # Disable metrics cache
      net.ipv4.tcp_rmem: 4096 87380 16777216      # Increase TCP read buffers
      net.ipv4.tcp_wmem: 4096 87380 16777216      # Increase TCP write buffers
      net.core.somaxconn: 32768                   # Higher connection queue
      # net.core.netdev_max_backlog: 50000        # Increase network buffer
      net.ipv4.tcp_max_syn_backlog: 30000         # More SYN requests
      net.ipv4.tcp_max_tw_buckets: 2000000        # Allow more TIME_WAIT sockets
    ulimits:
      nofile: 1048576    # Max open files (for RPC/WS connections)
      memlock: -1        # Disable memory locking limits (for in-memory DBs like MDBX)
    user: root
    ports:
      - ${PORT_P2P:-30353}:30303           # P2P TCP
      - ${PORT_P2P:-30353}:30303/udp       # P2P UDP
    expose:
      - 8545       # http
      - 8546       # websocket
      - 6060       # metrics
      - 8551
    entrypoint: /scripts/op-reth.sh
    command:
      - --datadir=/data
      - --log.stdout.format=json
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.port=${WS_PORT:-8546}
      - --ws.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots,flashbots,mev
      - --http
      - --http.corsdomain=*
      - --http.addr=0.0.0.0
      - --http.port=${RPC_PORT:-8545}
      - --http.api=admin,web3,debug,eth,net,trace,txpool,miner,rpc,reth,ots,flashbots,mev
      - --ipcpath=/data/reth.ipc
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=${AUTHRPC_PORT:-8551}
      - --authrpc.jwtsecret=/tmp/engine-auth-jwt
      - --metrics=0.0.0.0:${METRICS_PORT:-6060}
      - --max-outbound-peers=100
      - --chain=${CHAIN}
      - --rollup.disable-tx-pool-gossip
      - --discovery.port=${DISCOVERY_PORT:-30303}
      - --port=${P2P_PORT:-30303}
      # - --websocket-url=wss://mainnet.flashblocks.base.org/ws
      # - --config=/config/reth/reth.toml
      # - --engine.cross-block-cache-size=4096
      # - --max-inbound-peers=50
      # - --max-outbound-peers=50
      # - --nat=extip:${IP}
      # - --rollup.historicalrpc=https://mainnet-sequencer.optimism.io
      # - --rpc-cache.max-blocks=10000
      # - --rpc-cache.max-concurrent-db-requests=2048
      # - --rpc.gascap=600000000
      # - --rpc.max-blocks-per-filter=0
      # - --rpc.max-connections=50000
      # - --rpc.max-logs-per-response=0
    environment:
      OPSTACK_CHAIN: ${CHAIN}
      LETSENCRYPT_HOST: ${SUBDOMAIN:-opstack}.${HOST}
      VIRTUAL_HOST_MULTIPORTS: |-
        ${SUBDOMAIN:-opstack}.${HOST}:
          "/":
            port: 8545
            dest: "/"
          "/ws":
            port: 8546
            dest: "/"
    restart: unless-stopped
    stop_grace_period: 5m
    networks:
      - opstack
    volumes:
      - ${DATABASE_PATH:-data}:/data
      - ${SCRIPTS_PATH:-scripts}:/scripts
      - shared:/shared
    shm_size: 2gb

  # l2geth:
  #   profiles: ["optimism"]
  #   image: ethereumoptimism/l2geth:${L2GETH_TAG:-latest}
  #   container_name: ${COMPOSE_PROJECT_NAME}-l2geth
  #   restart: on-failure
  #   stop_grace_period: 5m
  #   entrypoint: 
  #     - /bin/sh
  #     - -c
  #     - "/scripts/init-l2geth.sh && /scripts/start-l2geth.sh"
  #   environment:
  #     USING_OVM: true
  #     ETH1_SYNC_SERVICE_ENABLE: false
  #     RPC_API: eth,rollup,net,web3,debug
  #     RPC_ADDR: 0.0.0.0
  #     RPC_CORS_DOMAIN: "*"
  #     RPC_ENABLE: true
  #     RPC_PORT: 8545
  #     RPC_VHOSTS: "*"
  #     BLOCK_SIGNER_ADDRESS: 0x00000398232E2064F896018496b4b44b3D62751F
  #     BLOCK_SIGNER_PRIVATE_KEY: 6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27
  #     BLOCK_SIGNER_PRIVATE_KEY_PASSWORD: pwd
  #     L2GETH_GENESIS_URL: https://storage.googleapis.com/optimism/mainnet/genesis-berlin.json
  #     L2GETH_GENESIS_HASH: 0x106b0a3247ca54714381b1109e82cc6b7e32fd79ae56fbcc2e7b1541122f84ea
  #     DATADIR: /geth
  #   volumes:
  #     - ${L2GETH_DATABASE_PATH:-l2geth}:/geth
  #     - ${SCRIPTS_PATH:-scripts}:/scripts/
  #   expose:
  #     - 8545 # http
  #     - 8546 # ws
  #   networks:
  #     - opstack

  # bedrock:
  #   profiles: ["optimism"]
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: Dockerfile.bedrock-init
  #   container_name: ${COMPOSE_PROJECT_NAME}-bedrock
  #   entrypoint: /scripts/bedrock.sh
  #   environment:
  #     OPSTACK_CHAIN: ${CHAIN}
  #     NODE_TYPE: ${NODE_TYPE}
  #   volumes:
  #     - ${DATABASE_PATH:-data}:/data
  #     - ${SCRIPTS_PATH:-scripts}:/scripts
  #     - shared:/shared
  #   networks:
  #     - opstack
