volumes:
  data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_data

networks:
  celo:
    name: celo

services:
  celo:
    image: us.gcr.io/celo-org/geth:mainnet
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - celo
    ports:
      - 30305:30305/tcp # p2p
      - 30305:30305/udp # p2p
    expose:
      - 8545 # http
      - 8546 # ws
    volumes:
      - ${DATABASE_PATH:-data}:/root/.celo/mainnet
    command: |
      --verbosity 3
      --syncmode full
      --gcmode archive
      --txlookuplimit=0
      --cache.preimages
      --port 30305
      --http
      --http.addr 0.0.0.0
      --http.api eth,net,web3,debug,admin,personal
      --light.serve 90
      --light.maxpeers 1000 
      --maxpeers 1100
      --datadir /root/.celo/mainnet
    environment:
      LETSENCRYPT_HOST: ${SUBDOMAIN:-celo}.${HOST}
      VIRTUAL_HOST_MULTIPORTS: |-
        ${SUBDOMAIN:-celo}.${HOST}:
          "/":
            port: 8545
            dest: "/"
          "/ws":
            port: 8546
            dest: "/"
            