chain: gnosis
datadir: /home/erigon/.local/share/erigon

externalcl: false
sync.loop.block.limit: 10_000
batchSize: 2g

# eth/66 peering
port: 30303

# download
torrent.port: 42069
torrent.download.rate: 1250mb
torrent.upload.rate: 1250mb

# gRPC Server
private.api.addr: localhost:9090 # for modular components connections

# Engine API (JWT auth)
authrpc.port: 8551 # for consensus layer communication
authrpc.addr: 0.0.0.0
authrpc.jwtsecret: /home/erigon/.local/share/erigon/jwt.hex
authrpc.vhosts: "*"

# HTTP & WebSockets & GraphQL
http: true
# http.compression : true 
http.port: 8545
http.addr: 0.0.0.0
http.vhosts: "*"
http.corsdomain: "*"
http.api: [eth, erigon, web3, debug, net, trace] # txpool
# rpc.returndata.limit: 1000000
# rpc.accessList : rules.json
ws: false
ws.compression: true

# metric
metrics : false
metrics.addr: 0.0.0.0
metrics.port: 6060

# pprof
pprof: false
pprof.addr: 0.0.0.0 
pprof.port: 6061

# snapshots: true
# snap.keepblocks: true
# db.size.limit: '8TB'
