volumes:
  data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_data

networks:
  scroll:
    name: ${COMPOSE_PROJECT_NAME}

services:
  scroll-mainnet:
    image: scrolltech/l2geth:${SCROLL_TAG:-scroll-v5.8.38}
    container_name: ${COMPOSE_PROJECT_NAME}
    expose: 
      - 8545 # HTTP server / GraphQL API 
    ports:
      - ${PORT_P2P:-38907}:38907
      - ${PORT_P2P:-38907}:38907/udp
    command:
      [
        "--scroll",
        "--scroll-mpt",
        "--syncmode=full",
        "--gcmode=${NODE_TYPE:-full}",
        "--cache.noprefetch",
        "--port=38907",
        "--ws",
        "--ws.port=8545",
        "--ws.addr=0.0.0.0",
        "--ws.origins=*",
        "--ws.api=eth,net,web3,debug,scroll",
        "--http",
        "--http.port=8545",
        "--http.addr=0.0.0.0",
        "--http.vhosts=*",
        "--http.corsdomain=*",
        "--http.api=eth,net,web3,debug,scroll",
        "--metrics",
        "--metrics.addr=0.0.0.0",
        "--metrics.port=6060",
        "--l1.endpoint=${SCROLL_L1_ENDPOINT}",
        "--da.sync",
        "--da.blob.beaconnode=${SCROLL_L1_BEACON}",
        "--da.blob.blobscan=https://api.blobscan.com/blobs/",
        "--da.blob.blocknative=https://api.ethernow.xyz/v1/blob/",
        "--rollup.verify",
        "--cache.snapshot=0",
        "--snapshot=false",
        "--txlookuplimit=0",
        # "--maxpeers=100",
        # "--gpo.ignoreprice=1",
        # "--graphql",
        # "--graphql.vhosts=*",
        # "--nat=extip:0.0.0.0", # megabytes of memory allocated to internal caching
        # "--cache=8192",
      ]
    networks:
      - scroll
    volumes:
      - ${DATABASE_PATH:-data}:/root/.ethereum
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      RUST_LOG: info
      CHAIN_ID: 534352
      LETSENCRYPT_HOST: ${SUBDOMAIN:-scroll}.${HOST}
      VIRTUAL_HOST_MULTIPORTS: |-
        ${SUBDOMAIN:-scroll}.${HOST}:
          "/":
            port: 8545
            dest: "/"
