#!/usr/bin/env sh

# exit script on any error
set -e

# Set Heimdall Home Directory
HEIMDALL_HOME=/root/.heimdall

if [ ! -f "$HEIMDALL_HOME/config/config.toml" ];
then
    echo "setting up initial configurations"
    /usr/bin/heimdalld init matic-moniker --chain-id=heimdallv2-137 --home=$HEIMDALL_HOME
    cd $HEIMDALL_HOME/config

    echo "removing autogenerated genesis file"
    rm genesis.json

    echo "downloading launch genesis file"
    wget -O genesis.json https://storage.googleapis.com/mainnet-heimdallv2-genesis/migrated_dump-genesis.json

    echo "overwriting toml config lines"
    # config.toml
    sed -i "s#^cors_allowed_origins.*#cors_allowed_origins = [\"*\"]#" config.toml
    sed -i "s#^seeds.*#seeds = \f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656,2eadba4be3ce47ac8db0a3538cb923b57b41c927@35.199.4.13:26656,3b23b20017a6f348d329c102ddc0088f0a10a444@35.221.13.28:26656,25f5f65a09c56e9f1d2d90618aa70cd358aa68da@35.230.116.151:26656\"#" config.toml
    # app.toml
    sed -i "s#^bor_rpc_url.*#bor_rpc_url = \"http://${MATIC_RPC_URL}\"#" app.toml
    sed -i "s#^eth_rpc_url.*#eth_rpc_url = \"http://${ETH_RPC_URL}\"#" app.toml
    #sed -i "s#^amqp_url.*#amqp_url = \"amqp://guest:guest@rabbitmq:5672\"#" app.toml
fi

# if [ "${BOOTSTRAP}" == 1 ] && [ -n "${SNAPSHOT_URL}" ] && [ ! -f "$HEIMDALLD_HOME/bootstrapped" ];
# then
#   echo "downloading snapshot from ${SNAPSHOT_URL}"
#   mkdir -p ${HEIMDALLD_HOME}/data
#   wget -c "${SNAPSHOT_URL}" -O - | tar -xz -C ${HEIMDALLD_HOME}/data && touch ${HEIMDALLD_HOME}/bootstrapped
# fi

exec heimdalld --home="$HEIMDALL_HOME" "$@"
