#!/usr/bin/env sh

# exit script on any error
set -e

# Set Heimdall Home Directory
HEIMDALL_HOME=/root/.heimdall

if [ ! -f "$HEIMDALL_HOME/config/config.toml" ];
then
    echo "setting up initial configurations"
    /usr/bin/heimdalld init matic-moniker --chain-id=heimdallv2-137 --home=$HEIMDALL_HOME
    cd $HEIMDALL_HOME/config

    echo "removing autogenerated genesis file"
    rm genesis.json

    echo "downloading launch genesis file"
    wget -O genesis.json https://storage.googleapis.com/mainnet-heimdallv2-genesis/migrated_dump-genesis.json

    echo "overwriting toml config lines"
    # config.toml
    sed -i "s#^cors_allowed_origins.*#cors_allowed_origins = [\"*\"]#" config.toml
    sed -i "s#^seeds.*#seeds = \"7f3049e88ac7f820fd86d9120506aaec0dc54b27@34.89.75.187:26656,2d5484feef4257e56ece025633a6ea132d8cadca@35.246.99.203:26656,72a83490309f9f63fdca3a0bef16c290e5cbb09c@35.246.95.65:26656,00677b1b2c6282fb060b7bb6e9cc7d2d05cdd599@34.105.180.11:26656,721dd4cebfc4b78760c7ee5d7b1b44d29a0aa854@34.147.169.102:26656,4760b3fc04648522a0bcb2d96a10aadee141ee89@34.89.55.74:26656\"#" config.toml
    # app.toml
    sed -i "s#^bor_rpc_url.*#bor_rpc_url = \"http://${MATIC_RPC_URL}\"#" app.toml
    sed -i "s#^eth_rpc_url.*#eth_rpc_url = \"http://${ETH_RPC_URL}\"#" app.toml
    #sed -i "s#^amqp_url.*#amqp_url = \"amqp://guest:guest@rabbitmq:5672\"#" app.toml
fi

# if [ "${BOOTSTRAP}" == 1 ] && [ -n "${SNAPSHOT_URL}" ] && [ ! -f "$HEIMDALLD_HOME/bootstrapped" ];
# then
#   echo "downloading snapshot from ${SNAPSHOT_URL}"
#   mkdir -p ${HEIMDALLD_HOME}/data
#   wget -c "${SNAPSHOT_URL}" -O - | tar -xz -C ${HEIMDALLD_HOME}/data && touch ${HEIMDALLD_HOME}/bootstrapped
# fi

exec heimdalld --home="$HEIMDALL_HOME" "$@"
