#!/usr/bin/env sh

# exit script on any error
set -e

normalize_url() {
    case "$1" in
        http://*|https://*)
            printf '%s' "$1"
            ;;
        *)
            printf 'http://%s' "$1"
            ;;
    esac
}

if [ ! -f "$HEIMDALL_DIR/config/config.toml" ];
then
    echo "setting up initial configurations"
    /usr/bin/heimdalld init matic-moniker --chain-id=heimdallv2-137 --home="$HEIMDALL_DIR"
    cd "$HEIMDALL_DIR/config"

    echo "removing autogenerated genesis file"
    rm genesis.json

    echo "downloading launch genesis file"
    wget -O genesis.json https://storage.googleapis.com/mainnet-heimdallv2-genesis/migrated_dump-genesis.json

fi

if [ -f "$HEIMDALL_DIR/config/config.toml" ] && [ -f "$HEIMDALL_DIR/config/app.toml" ];
then
    cd "$HEIMDALL_DIR/config"

    echo "overwriting toml config lines"
    # config.toml
    sed -i "s#^cors_allowed_origins.*#cors_allowed_origins = [\"*\"]#" config.toml
    sed -i "s#^seeds.*#seeds = \"a0ef6f328949adc077c59ab1f6b03711ae8d32d2@34.185.209.56:26656,f1e632758dfaf616a833900c0b8845bb2547b7c2@34.185.162.14:26656,e49bb5d9cb22943fb2b9f49a4c5d0f773917efaf@34.179.171.228:26656,babb8151d6fae45fcbb9229bd9faba173f3feaf3@35.246.166.189:26656,9c92984a5aad02c43955da94bb0a979a8dadbcfe@34.142.28.190:26656,3643aeae6a5965053709303e97257f62012fdd9c@34.39.56.114:26656,830d44b0d11ab25c9a03135859049d55daf73a03@34.147.169.102:26656,b0e795afc432ea3557b377d7763f6fb6dd102e60@34.105.180.11:26656\"#" config.toml

    bor_rpc_url=$(normalize_url "$MATIC_RPC_URL")
    eth_rpc_url=$(normalize_url "$ETH_RPC_URL")

    # app.toml
    sed -i "s#^bor_rpc_url.*#bor_rpc_url = \"${bor_rpc_url}\"#" app.toml
    sed -i "s#^eth_rpc_url.*#eth_rpc_url = \"${eth_rpc_url}\"#" app.toml
    sed -i "s#^amqp_url.*#amqp_url = \"${HEIMDALL_AMQP_URL}\"#" app.toml
fi

# if [ "${BOOTSTRAP}" == 1 ] && [ -n "${SNAPSHOT_URL}" ] && [ ! -f "$HEIMDALLD_HOME/bootstrapped" ];
# then
#   echo "downloading snapshot from ${SNAPSHOT_URL}"
#   mkdir -p ${HEIMDALLD_HOME}/data
#   wget -c "${SNAPSHOT_URL}" -O - | tar -xz -C ${HEIMDALLD_HOME}/data && touch ${HEIMDALLD_HOME}/bootstrapped
# fi

exec heimdalld --home="$HEIMDALL_DIR" "$@"
