volumes:
  config:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_config
  data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_data
  heimdall:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_heimdall

networks:
  matic:
    name: ${COMPOSE_PROJECT_NAME}

services:
  matic:
    image: erigontech/erigon:${ERIGON_TAG:-v3.0.14}
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - matic
    volumes:
      - ${CONFIG_PATH:-config}:/home/erigon/.config
      - ${DATABASE_PATH:-data}:/home/erigon/.local/share/erigon
    ports:
      - ${PORT_PEERING_66:-30323}:30303/tcp # eth/66 peering
      - ${PORT_PEERING_66:-30323}:30303/udp # eth/66 peering
      - ${PORT_PEERING_67:-30324}:30304/tcp # eth/67 peering
      - ${PORT_PEERING_67:-30324}:30304/udp # eth/67 peering
      - ${PORT_SNAP:-42089}:42069/tcp # snap sync
      - ${PORT_SNAP:-42089}:42069/udp # snap sync
      - ${PORT_SENTINEL_UDP:-4020}:4000/udp # sentinel peering (caplin)
      - ${PORT_SENTINEL_TCP:-4021}:4001/tcp # sentinel peering (caplin)
      # - 127.0.0.1:8565:8545/tcp # HTTP & WebSockets & GraphQL
    expose:
      - 9090/tcp # gRPC Server
      - 8551/tcp # Engine API (JWT auth)
      - 9091/tcp # incoming gRPC Connections
      - 6060/tcp # metric
      - 6061/tcp # pprof
      - 8545/tcp # HTTP & WebSockets & GraphQL
    command: >
      --config /home/erigon/.config/config.yaml
    mem_swappiness: 0
    user: ${ERIGON_UID:-1000}:${ERIGON_GID:-1000}
    environment:
      VIRTUAL_HOST: ${SUBDOMAIN:-matic}.${HOST}
      VIRTUAL_PORT: 8545
      LETSENCRYPT_HOST: ${SUBDOMAIN:-matic}.${HOST}

  heimdalld:
    image: 0xpolygon/heimdall-v2:${HEIMDALL_TAG:-0.2.16}
    container_name: ${COMPOSE_PROJECT_NAME}-heimdalld
    restart: unless-stopped
    volumes:
      - ${HEIMDALL_PATH:-heimdall}:/root/.heimdall
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - MATIC_RPC_URL=${COMPOSE_PROJECT_NAME}:8545
    ports:
      - 26656:26656 # P2P (TCP)
    expose:
      - 26657 # RPC (TCP)
    entrypoint: /root/.heimdall/heimdall-entrypoint.sh
    command:
      - start
      - --p2p.laddr=tcp://0.0.0.0:26656
      - --rpc.laddr=tcp://0.0.0.0:26657
      # - --fast_sync
      # - --p2p.upnp=false
      # - --pruning=syncable
      # - --with-tendermint=true
    networks:
      - matic

  heimdallr:
    image: 0xpolygon/heimdall-v2:${HEIMDALL_TAG:-0.2.16}
    container_name: ${COMPOSE_PROJECT_NAME}-heimdallr
    restart: unless-stopped
    volumes:
      - ${HEIMDALL_PATH:-heimdall}/heimdall
    ports:
      - 127.0.0.1:1317:1317 # Heimdall REST API
    depends_on:
      - heimdalld
    entrypoint: /root/.heimdall/heimdall-entrypoint.sh
    command:
      - rest-server
      - --laddr=tcp://0.0.0.0:1317
      - --node=tcp://${COMPOSE_PROJECT_NAME}-heimdalld:26657
      # - --max-open=1000
      # - --trust-node=true
    networks:
      - matic
