volumes:
  config:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_config
  data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_data

networks:
  matic:
    name: matic

services:
  matic:
    image: thorax/erigon:${MATIC_ERIGON_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - matic
    volumes:
      - ${CONFIG_PATH:-config}:/home/erigon/.config
      - ${DATABASE_PATH:-data}:/home/erigon/.local/share/erigon
    ports:
      - 30323:30303/tcp # eth/66 peering
      - 30323:30303/udp # eth/66 peering
      - 30324:30304/tcp # eth/67 peering
      - 30324:30304/udp # eth/67 peering
      - 42089:42069/tcp # snap sync
      - 42089:42069/udp # snap sync
      - 4020:4000/udp # sentinel peering (caplin)
      - 4021:4001/tcp # sentinel peering (caplin)
      - 127.0.0.1:8565:8545/tcp # HTTP & WebSockets & GraphQL
    expose:
      - 9090/tcp # gRPC Server
      - 8551/tcp # Engine API (JWT auth)
      - 9091/tcp # incoming gRPC Connections
      - 6060/tcp # metric
      - 6061/tcp # pprof
      # - 8545/tcp # HTTP & WebSockets & GraphQL
    command: >
      --config /home/erigon/.config/config.yaml
    mem_swappiness: 0
    user: ${ERIGON_UID:-1000}:${ERIGON_GID:-1000}
    environment:
      VIRTUAL_HOST: ${SUBDOMAIN:-matic}.${HOST}
      VIRTUAL_PORT: 8545
      LETSENCRYPT_HOST: ${SUBDOMAIN:-matic}.${HOST}