volumes:
  config:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_config
  data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_data
  heimdall:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_heimdall
  prometheus-data:
    name: ${COMPOSE_PROJECT_NAME}_prometheus
  grafana-data:
    name: ${COMPOSE_PROJECT_NAME}_grafana

networks:
  matic:
    name: ${COMPOSE_PROJECT_NAME}

services:
  matic:
    image: 0xpolygon/erigon:${ERIGON_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}
    sysctls:
      net.ipv4.tcp_slow_start_after_idle: 0
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_rmem: 4096 87380 16777216
      net.ipv4.tcp_wmem: 4096 87380 16777216
      net.core.somaxconn: 32768
      # net.core.netdev_max_backlog: 50000
      net.ipv4.tcp_max_syn_backlog: 30000
      net.ipv4.tcp_max_tw_buckets: 2000000
    ulimits:
      nofile: 1048576
      memlock: -1
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - matic
    volumes:
      - ${CONFIG_PATH:-config}:/home/erigon/.config
      - ${DATABASE_PATH:-data}:/home/erigon/.local/share/erigon
    ports:
      - ${PORT_PEERING_66:-30323}:30303/tcp # eth/66 peering
      - ${PORT_PEERING_66:-30323}:30303/udp # eth/66 peering
      - ${PORT_PEERING_67:-30324}:30304/tcp # eth/67 peering
      - ${PORT_PEERING_67:-30324}:30304/udp # eth/67 peering
      - ${PORT_SNAP:-42089}:42069/tcp # snap sync
      - ${PORT_SNAP:-42089}:42069/udp # snap sync
      - ${PORT_SENTINEL_UDP:-4020}:4000/udp # sentinel peering (caplin)
      - ${PORT_SENTINEL_TCP:-4021}:4001/tcp # sentinel peering (caplin)
      # - 127.0.0.1:8565:8545/tcp # HTTP & WebSockets & GraphQL
    expose:
      - 9090/tcp # gRPC Server
      - 8551/tcp # Engine API (JWT auth)
      - 9091/tcp # incoming gRPC Connections
      - 6060/tcp # metric
      - 6061/tcp # pprof
      - 8545/tcp # HTTP & WebSockets & GraphQL
    command: >
      --config /home/erigon/.config/config.yaml
    mem_swappiness: 0
    user: ${ERIGON_UID:-1000}:${ERIGON_GID:-1000}
    environment:
      VIRTUAL_HOST: ${SUBDOMAIN:-matic}.${HOST}
      VIRTUAL_PORT: 8545
      LETSENCRYPT_HOST: ${SUBDOMAIN:-matic}.${HOST}

  heimdalld:
    image: 0xpolygon/heimdall-v2:${HEIMDALL_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-heimdalld
    restart: unless-stopped
    volumes:
      - ${HEIMDALL_PATH:-heimdall}:/root/.heimdall
    environment:
      - HEIMDALL_ETH_RPC_URL=${ETH_RPC_URL}
    ports:
      - 26656:26656 # P2P (TCP)
    expose:
      - 26657 # RPC (TCP)
    entrypoint: /root/.heimdall/heimdall-entrypoint.sh
    command:
      - start
      - --home=/root/.heimdall
      - --rest-server=false
    networks:
      - matic

  heimdallr:
    image: 0xpolygon/heimdall-v2:${HEIMDALL_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-heimdallr
    restart: unless-stopped
    environment:
      - HEIMDALL_ETH_RPC_URL=${ETH_RPC_URL}
    volumes:
      - ${HEIMDALL_PATH:-heimdall}:/root/.heimdall
    expose:
      - 1317 # Heimdall REST API
    depends_on:
      - heimdalld
    command:
      - start
      - --home=/root/.heimdall
      - --rest-server=true
      - --node=tcp://${COMPOSE_PROJECT_NAME}-heimdalld:26657

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: ${COMPOSE_PROJECT_NAME}-prometheus
    user: ${ERIGON_UID:-1000}:${ERIGON_GID:-1000}
    command: 
      - '--log.level=warn' 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=150d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - matic

  grafana:
    image: grafana/grafana:10.4.2
    container_name: ${COMPOSE_PROJECT_NAME}-grafana
    user: "472:0"
    expose:
      - 3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION: true
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
      PROMETHEUS_HOST: ${COMPOSE_PROJECT_NAME}-prometheus
      VIRTUAL_HOST: ${SUBDOMAIN:-matic}-dashboard.${HOST}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${SUBDOMAIN:-matic}-dashboard.${HOST}
    restart: unless-stopped
    networks:
      - matic
