volumes:
  config:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_config
  c-config:
    external: true
    name: ${COMPOSE_PROJECT_NAME}-c_config

networks:
  avalanche:
    name: avalanche

services:
  avalanche:
    image: avaplatform/avalanchego:${AVALANCHE_TAG-v1.11.9}
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - avalanche
    ports:
      - 127.0.0.1:9650:9650
    expose:
      # - 9650
      - 9651
    volumes:
      - /data/avalanche:/root/.avalanchego
      - config:/root/.avalanchego/configs/
      - c-config:/root/.avalanchego/configs/chains/C
    command: 
      [
        "/avalanchego/build/avalanchego",
        "--db-dir=/root/.avalanchego",
        # "--api-admin-enabled=true",
        "--http-host=",
        # "--bootstrap-beacon-connection-timeout=10m0s",
        "--http-allowed-hosts=*"
      ]
    environment:
      LETSENCRYPT_HOST: avalanche.${HOST}
      VIRTUAL_HOST_MULTIPORTS: |-
        avalanche.${HOST}:
          "/":
            port: 9650
            dest: "/ext/bc/C/rpc"
          "/ws":
            port: 9650
            dest: "/ext/bc/C/ws"
