chain : bor-mainnet
datadir : /datadir

snapshots : false 
snap.stop : true
bor.heimdall : https://heimdall.stakesystems.io 

http : true 
http.addr : 0.0.0.0 
http.port : 8545 
http.compression : true
http.vhosts : '*' 
http.corsdomain : '*' 
http.api : [eth,debug,net,trace,web3,erigon,bor]

ws : true
ws.compression : true

rpc.gascap : 300000000
rpc.batch.limit : 200000 

metrics : true
metrics.addr : 0.0.0.0 
metrics.port : 6060

bodies.cache : 5G 

db.pagesize : 16k 
batchSize : 2048MB 
port : 61044 
p2p.protocol : 66 
ethash.dagdir : /datadir/ethash
rpc.returndata.limit : 1000000